-- project_progress (15 rows)
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (1, 2, '요구사항 분석', 1, '완료', 100, '요구사항 분석 단계 완료', '요구사항 분석_산출물.pdf', '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (2, 2, '화면설계', 2, '완료', 100, '화면설계 단계 완료', '화면설계_산출물.pdf', '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (3, 2, '핵심 개발', 3, '진행중', 60, '핵심 개발 단계 진행 중 (60%)', NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (4, 2, '통합 테스트', 4, '예정', 0, NULL, NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (5, 2, '최종 검수', 5, '예정', 0, NULL, NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (6, 7, '요구사항 분석', 1, '완료', 100, '요구사항 분석 단계 완료', '요구사항 분석_산출물.pdf', '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (7, 7, '화면설계', 2, '완료', 100, '화면설계 단계 완료', '화면설계_산출물.pdf', '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (8, 7, '핵심 개발', 3, '완료', 100, '핵심 개발 단계 완료', NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (9, 7, '통합 테스트', 4, '완료', 100, '통합 테스트 단계 완료', NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (10, 7, '최종 검수', 5, '완료', 100, '최종 검수 단계 완료', NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (11, 9, '요구사항 분석', 1, '완료', 100, '요구사항 분석 단계 완료', '요구사항 분석_산출물.pdf', '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (12, 9, '화면설계', 2, '진행중', 60, '화면설계 단계 진행 중 (60%)', NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (13, 9, '핵심 개발', 3, '예정', 0, NULL, NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (14, 9, '통합 테스트', 4, '예정', 0, NULL, NULL, '2026-06-25 15:00:00');
INSERT INTO project_progress (id, sample_event_id, stage_name, stage_order, status, progress_rate, updated_note, deliverable_name, updated_at) VALUES (15, 9, '최종 검수', 5, '예정', 0, NULL, NULL, '2026-06-25 15:00:00');
