-- sample_events (10 rows)
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (1, '2026 인천 청년 창업 해커톤', '해커톤·아이디어톤', '인천경제자유구역청', '2026-08-01', '2026-08-02', '인천', '오프라인', 120, 45000000, '지역 청년의 창업 아이디어 발굴 및 초기 팀 빌딩 지원', '인천창업해커톤_과업지시서.pdf', 'quoted');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (2, 'AI 스타트업 부트캠프 3기', '부트캠프·창업캠프', 'OO테크노파크', '2026-08-16', '2026-10-10', '경기', '하이브리드', 60, 80000000, 'AI 기반 초기 스타트업 대상 8주 집중 육성 프로그램', 'AI부트캠프3기_제안요청서.docx', 'in_progress');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (3, '2026 데모데이 IR 피칭 페스타', '데모데이·IR피칭', 'OO창조경제혁신센터', '2026-08-12', '2026-08-12', '서울', '오프라인', 200, 60000000, '투자 유치를 위한 스타트업 IR 피칭 및 VC 네트워킹', NULL, 'draft');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (4, '제조 스타트업 기술 경진대회', '경진대회', '중소벤처기업진흥공단 OO지부', '2026-08-10', '2026-08-10', '대전', '오프라인', 80, 35000000, '제조 분야 기술 창업팀 발굴 및 시상', NULL, 'draft');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (5, '글로벌 진출 네트워킹 나이트', '네트워킹', 'OO상공회의소', '2026-08-12', '2026-08-12', '서울', '오프라인', 150, 25000000, '해외 진출 희망 기업과 현지 파트너사 간 네트워킹', '네트워킹나이트_기획요청.pdf', 'quoted');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (6, '2026 미래산업 포럼', '포럼·컨퍼런스', 'OO경제자유구역청', '2026-08-05', '2026-08-05', '인천', '하이브리드', 300, 90000000, '미래 신산업 트렌드 공유 및 정책 방향 논의', NULL, 'draft');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (7, '여성 창업가 특강 시리즈', '특강·세미나', 'OO여성기업종합지원센터', '2026-08-15', '2026-09-18', '부산', '온라인', 100, 15000000, '여성 창업가 대상 실무 역량 강화 특강 5회 시리즈', '여성창업특강_기획안.hwp', 'confirmed');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (8, '청년 일자리 박람회', '박람회·전시', 'OO시청 일자리경제과', '2026-08-20', '2026-08-21', '광주', '오프라인', 500, 70000000, '지역 기업-구직 청년 매칭 박람회', NULL, 'draft');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (9, '아이디어톤 with 대학생', '해커톤·아이디어톤', 'OO대학교 산학협력단', '2026-08-17', '2026-08-18', '강원', '오프라인', 90, 20000000, '대학생 대상 지역 문제 해결형 아이디어톤', '대학생아이디어톤_제안요청서.pptx', 'in_progress');
INSERT INTO sample_events (id, event_name, event_type, organizer, period_start, period_end, region, operation_type, participant_scale, budget_limit, purpose, uploaded_document_name, status) VALUES (10, '문화콘텐츠 스타트업 데모데이', '데모데이·IR피칭', 'OO문화재단', '2026-08-11', '2026-08-11', '전북', '오프라인', 70, 28000000, '문화콘텐츠 분야 스타트업 투자 유치 데모데이', NULL, 'draft');
